version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:1q2w3e@db:5432/postgres
    depends_on:
      - db
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm run dev

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
